# Generated by Django 3.2.7 on 2021-10-11 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shorturl',
            old_name='original',
            new_name='original_link',
        ),
        migrations.RenameField(
            model_name='shorturl',
            old_name='short_link',
            new_name='short_name',
        ),
    ]
