# Generated by Django 3.2.7 on 2021-10-14 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0002_auto_20211011_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='shorturl',
            name='cr_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
