# Generated by Django 3.2.7 on 2021-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('short', '0004_alter_shorturl_cr_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorturl',
            name='short_name',
            field=models.CharField(max_length=15),
        ),
    ]
