# Generated by Django 3.2.7 on 2021-10-14 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='visit_no',
            field=models.IntegerField(default=0),
        ),
    ]
