# Generated by Django 3.2.7 on 2021-10-14 15:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0002_tree_visit_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='cr_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
