# Generated by Django 3.2.7 on 2021-10-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0003_tree_cr_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tree',
            name='visit_no',
        ),
    ]
