# Generated by Django 3.2.7 on 2021-10-14 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tree', '0004_remove_tree_visit_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='short_name',
            field=models.CharField(max_length=30),
        ),
    ]
